all:	sort


sort:	bubble.c bucket.c insertion.c shaker.c quick.c tree.c
	cc bubble.c -o bubble
	cc bucket.c -o bucket
	cc insertion.c -o insertion
	cc shaker.c -o shaker
	cc quick.c -o quick
	cc tree.c -o tree

clean:
	-rm bubble bucket insertion shaker quick tree