folder_hasil=bin/

all:	program

program:	rand.c area.c height.c
		cc rand.c -o ${folder_hasil}rand -lm
		cc area.c -o ${folder_hasil}area -lm
		cc roullete.c -o ${folder_hasil}roullete -lm		
		cc height.c -o ${folder_hasil}height -lm
		cc bingo.c -o ${folder_hasil}bingo -lm


clean:
		rm bin/*